blog/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls.defaults import *
from django.views.generic.dates import *
from django.views.generic import ListView
from django.views.generic.simple import direct_to_template

import views

urlpatterns = patterns('',
    url(r"^$", views.BlogListView.as_view(),  name="list"),
    url(r"^blog/(?P<slug>[\w-]+)/$", views.PostDetailView.as_view(), name="detail"),
)

microblog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# from . import views
from blog.views import BlogListView, HomepageView

import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r"^$", HomepageView.as_view(),  name="home"),
    url(r'^blog/', include('blog.urls', namespace='blog')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
        (r'^static(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),

)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class PostManager(models.Manager):
   def live(self):
      return self.model.objects.filter(published=True)


class Post(models.Model):
   created_at = models.DateTimeField(auto_now_add=True, editable=False)
   updated_at = models.DateTimeField(auto_now_add=True, editable=False)
   title = models.CharField(max_length=255)
   slug = models.SlugField(max_length=255, blank=True, default='')
   content = models.TextField()
   published = models.BooleanField(default=True)
   author = models.ForeignKey(User, related_name="posts")
   objects = PostManager()

   class Meta:
      ordering = ["-created_at", "title"]


   def __unicode__(self):
      return self.title

   def save(self, *args, **kwargs):
      if not self.slug:
          self.slug = slugify(self.title)
      super(Post, self).save(*args, **kwargs)

   @models.permalink
   def get_absolute_url(self):
      return ("blog:detail", (), {"slug": self.slug})

blog/views.py
from django.views.generic import ListView, DetailView, TemplateView

from models import Post


class HomepageView(TemplateView):
   template_name = 'index.html'


class PublishedPostsMixin(object):
    def get_queryset(self):
        # queryset = super(PublishedPostsMixin, self).get_queryset()
        # return queryset.filter(published=True)
        return self.model.objects.live()

class BlogListView(PublishedPostsMixin, ListView):
    model = Post


class PostDetailView(PublishedPostsMixin, DetailView):
    model = Post

blog/templates/blog/post_detail.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_title %} {{ post.title}} | {% endblock %}

{% block page_content %}
<h2>{{ post.title }}</h2>
{{ post.content|linebreaks }}
<p>{{ post.updated_at }}</p>
<p><a href="{% url 'blog:list' %}">&larr; Blog list</a></p>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
<h1>Blog Posts</h1>
<ul>
    {% for post in post_list %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% empty %}
    <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
</ul>
{% endblock %}

microblog/templates/_layouts/base.html
<!doctype html>
<html>
    <head>
    	<link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
        <title>{% block page_title %}{% endblock %}Microblog</title>
    </head>
    <body>
    	<div class="container">
        	{% block page_content %}{% endblock %}
    	</div>
    </body>
</html>

microblog/templates/index.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
<h1>Welcome to my site</h1>

<a href="{% url 'blog:list' %}" class='btn'>Read my Blog</a>

{% endblock %}